# Generated by Django 4.1.7 on 2023-06-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuarios', '0002_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nome',
        ),
    ]
